---
name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger:
    uses: statnett/github-workflows/.github/workflows/release-please.yaml@main
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
